### ISSUE TITLE
upcloud is not working

### ISSUE THREAD

**Issue by ownerHZH** [crypto-0/sol-cli#1]
decrypt_ed = decrypt((url).encode('utf-8'), key).decode('utf-8').lstrip(' ')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte

**Comment by crypto-0** [comment]
Upcloud should be working now  but if there is still an issue let me know the error along with any arguments supplied to the application and I will work on it .

**Comment by aditya-shri** [comment]
Same error for Vidcloud

**Comment by crypto-0** [comment]
it should be fixed now seems wrong key was being used as it changed.
